# Generated by Django 5.1.4 on 2024-12-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_billpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillPayment',
        ),
    ]
